# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bravros < Formula
  desc "Bravros — free, public, host-neutral agent toolkit"
  homepage "https://bravros.dev"
  version "2.13.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bravros/bravros/releases/download/v2.13.1/bravros-darwin-amd64.tar.gz"
      sha256 "e9f80264bb362dcbf5a47de3893e86e974c2594b843e061bf537b15347a77c31"

      define_method(:install) do
        bin.install "bravros"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bravros/bravros/releases/download/v2.13.1/bravros-darwin-arm64.tar.gz"
      sha256 "083a3aa811850eb644f6be61959508977bbda511a8e98bc292a0c1d13e37aeb5"

      define_method(:install) do
        bin.install "bravros"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bravros/bravros/releases/download/v2.13.1/bravros-linux-amd64.tar.gz"
      sha256 "1dec54dd52ab07ef268c718dae86aa2c02c1ccbcca4dd46c36d38dc83def0a24"
      define_method(:install) do
        bin.install "bravros"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bravros/bravros/releases/download/v2.13.1/bravros-linux-arm64.tar.gz"
      sha256 "cc91f7a56af2612d4108e254f79297b699051c5279f4f50c4f4b3d4af3c23c0b"
      define_method(:install) do
        bin.install "bravros"
      end
    end
  end

  def caveats
    <<~EOS
      Run `bravros init` to initialize the project, install hooks, and configure Claude Code.
    EOS
  end

  test do
    system "#{bin}/bravros", "version"
    # Match the actual lowercase "bravros vX.Y.Z" emitted by `bravros version`.
    # The previous "Bravros" (capital B) was case-sensitive and broke `brew test`.
    assert_match(/^bravros v\d+\.\d+\.\d+/, shell_output("#{bin}/bravros version"))
  end
end
