# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bravros < Formula
  desc "Bravros — free, public, host-neutral agent toolkit"
  homepage "https://bravros.dev"
  version "2.12.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bravros/bravros/releases/download/v2.12.0/bravros-darwin-amd64.tar.gz"
      sha256 "e4827dc9cd621389510aabb81287cca254364f320c68b3fa35df777dd40575ae"

      define_method(:install) do
        bin.install "bravros"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bravros/bravros/releases/download/v2.12.0/bravros-darwin-arm64.tar.gz"
      sha256 "d580ddf6dfe5917a5b2087bb25aa3868398647df8dd04780b5dc66514e1d5172"

      define_method(:install) do
        bin.install "bravros"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bravros/bravros/releases/download/v2.12.0/bravros-linux-amd64.tar.gz"
      sha256 "37a8d8c3af0e031f6e54b55ada6ea3eba12482521d7d6ab6d93d11667e0c2cfe"
      define_method(:install) do
        bin.install "bravros"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bravros/bravros/releases/download/v2.12.0/bravros-linux-arm64.tar.gz"
      sha256 "1d6f12895697f12009d2d5031f83b0885c7d0a491cf22a79b7d71a331f7402a3"
      define_method(:install) do
        bin.install "bravros"
      end
    end
  end

  def caveats
    <<~EOS
      Run `bravros init` to initialize the project, install hooks, and configure Claude Code.
    EOS
  end

  test do
    system "#{bin}/bravros", "version"
    # Match the actual lowercase "bravros vX.Y.Z" emitted by `bravros version`.
    # The previous "Bravros" (capital B) was case-sensitive and broke `brew test`.
    assert_match(/^bravros v\d+\.\d+\.\d+/, shell_output("#{bin}/bravros version"))
  end
end
