# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bravros < Formula
  desc "Bravros — free, public, host-neutral agent toolkit"
  homepage "https://bravros.dev"
  version "2.9.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bravros/bravros/releases/download/v2.9.1/bravros-darwin-amd64.tar.gz"
      sha256 "efbd420c4ec8808b7a6dfa08719ee2be85aa922bd39686684dee4e8608dd011f"

      define_method(:install) do
        bin.install "bravros"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bravros/bravros/releases/download/v2.9.1/bravros-darwin-arm64.tar.gz"
      sha256 "9663c0bde76ea944a66fadd53beda41539bdda14272085eaf8ae24185fb91f70"

      define_method(:install) do
        bin.install "bravros"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bravros/bravros/releases/download/v2.9.1/bravros-linux-amd64.tar.gz"
      sha256 "12d37cc533c6781333a2834e06a7778308827a7bd88ff2ab64003161ec415e74"
      define_method(:install) do
        bin.install "bravros"
      end
    end
  end

  def caveats
    <<~EOS
      Run `bravros init` to initialize the project, install hooks, and configure Claude Code.
    EOS
  end

  test do
    system "#{bin}/bravros", "version"
    # Match the actual lowercase "bravros vX.Y.Z" emitted by `bravros version`.
    # The previous "Bravros" (capital B) was case-sensitive and broke `brew test`.
    assert_match(/^bravros v\d+\.\d+\.\d+/, shell_output("#{bin}/bravros version"))
  end
end
